apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
  - ../../base
  - configmap.yaml

commonLabels:
  env: uat

images:
  - name: pos-app
    newName: ghcr.io/zawthanoo/pos-app
    newTag: 1.0.0-8-07fb7e

replicas:
  - name: pos-app
    count: 2
